#!/usr/bin/env python

import argparse
import cookielib
import glob
import os
import os.path
import shutil
import urllib
import urllib2

CODEEVAL_URL = 'https://www.codeeval.com'

def create_challenge(args):
	challenge_name = args.challenge_name.lower().replace(' ', '_')
	filename_root  = '{0}_{1}'.format(args.challenge_id, challenge_name)

	for lang in os.listdir('.'):
		if not os.path.isdir(lang) or lang.startswith('.'):
			continue

		template_match = glob.glob(os.path.join(lang, 'template.*'))
		if len(template_match) == 0:
			continue

		template = template_match[0]
		filename = os.path.join(lang, filename_root) + os.path.splitext(template)[1]

		if os.path.exists(filename):
			print 'Skipping {0}...'.format(filename)
		else:
			print 'Creating {0}...'.format(filename)

			shutil.copyfile(template, filename)

def login(args):
	policy     = cookielib.DefaultCookiePolicy(allowed_domains = [CODEEVAL_URL])
	cookie_jar = cookielib.FileCookieJar('codeeval.cookie', policy = policy)
	opener     = urllib2.build_opener(urllib2.HTTPCookieProcessor(cookie_jar))
	data       = { 'username': args.username, 'password': args.password }

	res = opener.open(CODEEVAL_URL + '/accounts/login', urllib.urlencode(data))

if __name__ == '__main__':
	parser = argparse.ArgumentParser(description = 'Create solution files for each language for a challenge')
	subparsers = parser.add_subparsers()

	create_parser = subparsers.add_parser('create')
	create_parser.add_argument('challenge_id', type = int,
						help = 'Challenge ID')
	create_parser.add_argument('challenge_name', type = str,
						help = 'Challenge name')
	create_parser.set_defaults(func = create_challenge)

	login_parser = subparsers.add_parser('login')
	login_parser.add_argument('username', type = str)
	login_parser.add_argument('password', type = str)
	login_parser.set_defaults(func = login)

	args = parser.parse_args()
	args.func(args)

